### ISSUE TITLE
Device class missing from NuGet distribution

### ISSUE THREAD

**Issue by ciband** [1iveowl/SSDP.UPnP.PCL#12]
I pulled in the NuGet package into my .NET Core application and it appears that the SSDP.UPnP.PCL.dll assembly is missing.  I downloaded the 3.7.0 version and it is present.

Thanks.

**Comment by 1iveowl** [comment]
Hmm, not sure. Anyhow, I'm working on an update and have fixed some bugs. 

Could you try the just release 3.8.0-beta1 (find it under previews) and see if it's better?

**Comment by ciband** [comment]
Just saw your comment.  Please see my revised original post.

**Comment by ciband** [comment]
Tried the beta.  The assembly still appears to be missing.

![image](https://cloud.githubusercontent.com/assets/18743679/25688317/b72b0066-3043-11e7-9313-ffc123e1f194.png)

**Comment by 1iveowl** [comment]
OK. Thanks. I will look into it.

**Comment by ciband** [comment]
thank you.  Using 3.7.0 and its getting me down the road.  thanks for the library.

**Comment by 1iveowl** [comment]
There was a bug in the nuspec file. Try 3.8.0-beta2.

**Comment by ciband** [comment]
That got it.  thanks.
