### ISSUE TITLE
Exception on CreateMSearchObservable

### ISSUE THREAD

**Issue by sensboston** [1iveowl/SSDP.UPnP.PCL#17]
I'm trying to use your library for the simple DLNA renderer (for some reasons I'm using WinForms), but always getting exception saying "Only one usage of each socket address (protocol/network address/port) is normally permitted" on this line of code:
`var mSearchObservable = await _device.CreateMSearchObservable();`

My PC has a few network adapters. Could you suggest some fix or workaround?

**Comment by 1iveowl** [comment]
I'm not sure. Have you tried disabling the Windows SSDP Service?

**Comment by 1iveowl** [comment]
Now I remember. 

GetHttpListener is overloaded and accepts a CommunicationInterface. See [SocketLite](https://github.com/1iveowl/SocketLite#specify-which-network-interface-to-use) for how to create it. 

Let me know if this is helpful?

**Comment by sensboston** [comment]
Actually, I got rid from this error by changing **false** to **true** in
```
var multicastReqObs = await _httpListener.UdpMulticastHttpRequestObservable(
                Initializer.UdpSSDPMultiCastAddress,
                Initializer.UdpSSDPMulticastPort,
                true);
```

**Comment by 1iveowl** [comment]
Ahh, good. Forget about this. Been a while since I created the library.

**Comment by 1iveowl** [comment]
Feel free to do a pull request on the documentation if there is something here that need to be added.

**Comment by sensboston** [comment]
I'm really sorry, but I switched to https://github.com/Yortw/RSSDP: it works out of box, and adds much-much less "overhead" to my project...

**Comment by 1iveowl** [comment]
Don't be sorry. If the other project works for you then use it :-)

The project is great if you like Reactive Extensions. However, I realize that Rx is not for everyone.

**Comment by 1iveowl** [comment]
Oh, and RSSDP is for UPnP 1.1. This project is for UPnP 2.0, however in many cases it really doesn't matter.
