### ISSUE TITLE
Cant install NuGet package

### ISSUE THREAD

**Issue by Syr0kx** [1iveowl/SSDP.UPnP.PCL#25]
I get an error, that the packet "SimpleHttpListen" version (>=6.0.5) could not be found.
The latest version is 5.1.2 but I guess it should reference to "SimpleHttpListener.Rx" which has a version 6.0.5

**Comment by 1iveowl** [comment]
You are absolutely correct. There's a bug in the NuGet. Will be fixed in a few minutes. 

Please look out for version 6.0.2 of SSDP.UPnP.PCL.
