### ISSUE TITLE
Usage of library

### ISSUE THREAD

**Issue by modplug** [1iveowl/SSDP.UPnP.PCL#4]
Pardon my ignorance but is this library for connecting to remote UPNP servers, setting up your own server or both?

I'm one of the contributors to https://github.com/martijn00/XamarinMediaManager  and I would like to be able to discover UPNP servers and playback media from them.

Hope to hear from you soon,

keep up the good work :)

**Comment by 1iveowl** [comment]
It's only the SSDP part of the UPnP protocol. 

To get an overview of UPnP see here: [UPnP Technical basics](http://upnp.org/resources/documents/UPnP_UDA_tutorial_July2014.pdf)

For the details see the specification: [UPnP Architecture documentation](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf)

I'm also working on the other parts. So far I've implemented the Eventing part for a UPnP Control Point partially but I'm not quite ready to share that just yet. 

It's just a hobby so don't hold your breath ;-)
