### ISSUE TITLE
MSearchRequest is internal

### ISSUE THREAD

**Issue by jcoutch** [1iveowl/SSDP.UPnP.PCL#6]
I'm trying to follow the example source code in readme.md, but noticed in your last example...
```
var mSearchMessage = new MSearch
{
    SearchCastMethod = CastMethod.Multicast,
    CPFN = "myFriendlyNameOfThisControlPoint",
    HostIp = "239.255.255.250",     // Must be this IP - i.e. this is a multicast 
    HostPort = 1900,               // Must be port 1900 as defined in th specification
    MX = TimeSpan.FromSeconds(1),
    ST = "upnp:rootdevice",
    UserAgent = new UserAgent
    {
        OperatingSystem = "Windows",
        OperatingSystemVersion = "10.0",
        ProductName = "SSDP.UPNP.PCL",
        ProductVersion = "0.9",
        UpnpMajorVersion = "2",
        UpnpMinorVersion = "0",
    }
};

await controlPoint.SendMSearch(mSearchMessage);
```

...MSearch doesn't exist.  The only places I found it were in your Test projects.  So, noticing that SendMSearchAsync takes an IMSearchRequest, I tried to create an instance of MSearchRequest...but it's an internal class.  :-(

**Comment by 1iveowl** [comment]
Thank you jcoutch. I agree that the Readme is not particular clear on this point. 

MSearch does indeed not exist. You need to create that class yourself and it must implement the interface `IMSearchRequest`

I've now updated the readme to reflect this.

**Comment by 1iveowl** [comment]
Was this helpful?

**Comment by jcoutch** [comment]
Yes.  Thank you!
